### ISSUE TITLE
Other planet biome in earth

### ISSUE THREAD

**Issue by Hacker6400** [JameH2/Hbm-s-Nuclear-Tech-GIT#100]
I was exploring my world and i notice that sometimes spawns a little chunk of moho biome and silt from another planet that i don't remember the name

**Comment by JameH2** [comment]
Oh godammit mojang yeah sorry apparently biome ids can ONLY be up to 128 otherwise they spawn on the overworld… for some reason

Anyway just find the moho biome id in cfg and change it to below 128. Ill fix it in the code soon
