### ISSUE TITLE
Alkylation unit port broken

### ISSUE THREAD

**Issue by Hacker6400** [JameH2/Hbm-s-Nuclear-Tech-GIT#104]
I was testing the alkylation unit when i notice that in one part of it, the ducts don't connect. 
It's only a graphic bug because it work fine
Here the images
![Screenshot_2024-08-13-23-01-25-489_net kdt pojavlaunch](https://github.com/user-attachments/assets/03870047-f5f8-4ffd-93fc-856d688748fb)
![Screenshot_2024-08-13-23-01-44-251_net kdt pojavlaunch](https://github.com/user-attachments/assets/09b25ae0-543a-4bb1-b4f9-bacbc8b0c4ba)
![Screenshot_2024-08-13-23-01-39-952_net kdt pojavlaunch](https://github.com/user-attachments/assets/614e65e4-8d6d-4170-be7b-de2a372b128b)
![Screenshot_2024-08-13-23-01-35-115_net kdt pojavlaunch](https://github.com/user-attachments/assets/6a0b452f-2369-442d-88f9-6fbe7e441180)

**Comment by MellowArpeggiation** [comment]
Fixed in upcoming release, thanks for the report!
