### ISSUE TITLE
Remove political content

### ISSUE THREAD

**Issue by NarekoMichigami810** [JameH2/Hbm-s-Nuclear-Tech-GIT#106]
When I was translating NTM-S, I found that Cn-989 is a political item. I don't want political content to appear in the game, so I hope you can change or remove it to facilitate my translation work.

**Comment by username228a91** [comment]
lmao

**Comment by MellowArpeggiation** [comment]
I'm not sure I understand the issue, what is political about the item?

**Comment by username228a91** [comment]
> I'm not sure I understand the issue, what is political about the item?

winnie pooh has came for his life

**Comment by HbmMods** [comment]
lmao

**Comment by FatSassin** [comment]
小熊維尼在我家門口，它在做什麼哦上帝，中國秘密警察破門而入，救救我！

**Comment by Hacker6400** [comment]
Here +♾️ social credit, now they can't arrest you
