### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Herr-Roin** [JameH2/Hbm-s-Nuclear-Tech-GIT#108]
Hello. At first I really want to thank you for doing so much work. You really make players have an amazing experience and this even for free. 

Before I Start a Survival project with this mod, id like to ask if the mod is ready to do such a project without experiencing too many bugs. I know its in beta, but do you think I can Start?

Also, if I would start now and use the currently latest file of the mod and it gets updated over time, can I just replace the older version with the newer without my World getting lost?

**Comment by SuperTechxter** [comment]
i am no dev or anything but i would wait a bit more time to fully flush out the mod and make as little as bugs agin later on

**Comment by MellowArpeggiation** [comment]
Hey, thanks for the support!
Yes, the mod is fully ready for survival play, and as we release updates you can remove the old versions and replace them with the new ones without issue. We strive to make sure that we aren’t going to break any existing saves with updates (we play the mod a _lot_ too!)
