### ISSUE TITLE
Some machine guis don't report fluid level

### ISSUE THREAD

**Issue by thePalindrome** [JameH2/Hbm-s-Nuclear-Tech-GIT#116]
So far I've seen the Oil Derrick and ZIRNOX report 0mb for fluids that they're actually full in (as can be proven by interactions with other things), although the Oil Refinery *does* report the numbers, and anything that has the "hover over tooltip" seems to report numbers just fine as well

**Comment by Hacker6400** [comment]
It a problem from the main ntm version
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/discussions/1638

**Comment by thePalindrome** [comment]
It's apparently already fixed, I haven't followed the project too long so I don't know how long it'd roughly take to merge in the fix

**Comment by MellowArpeggiation** [comment]
Latest commits have the fix already, James has just been away from computer for a bit

**Comment by thePalindrome** [comment]
Well, wasn't sure if James does a weekly merge in or whatnot, but yeah, hopefully someone with push access can fix things (I'm also hoping it fixes another issue I'm having a hard time traiging)

**Comment by MellowArpeggiation** [comment]
He or I will merge whenever NTMain releases a new version, and I've merged in the latest fixes from main myself, I just don't have a way to push builds to modrinth.
