### ISSUE TITLE
oil derricks lose their connectors

### ISSUE THREAD

**Issue by moobleh** [JameH2/Hbm-s-Nuclear-Tech-GIT#119]
Logged in to my server today and noticed all the oil derricks have lost their connectors, even newley placed ones.
![2024-08-22_17 04 20](https://github.com/user-attachments/assets/8b3d845f-b907-49f5-8891-26607a18c3a5)
![2024-08-22_17 04 36](https://github.com/user-attachments/assets/8b63cbd9-0c9a-4c60-bb2e-a59ed6f00df3)

**Comment by JameH2** [comment]
New model, new ports

**Comment by JameH2** [comment]
Remind me to never use git on my phone

**Comment by thePalindrome** [comment]
I found you had to break and re-place it to "open up" the spots where cables and pipes go

**Comment by moobleh** [comment]
were are the new ports? ive replaced them but cant see anywere to plug things in. that or im horrendously blind

**Comment by moobleh** [comment]
![2024-08-22_22 48 54](https://github.com/user-attachments/assets/5558cf71-f945-41d0-b3f5-7ce040dd6e61)
OH nevermind, i am blind
