### ISSUE TITLE
[Enhancement] Bring "Press F1 for help" menu from Main HBM's NTM

### ISSUE THREAD

**Issue by Millymilo00** [JameH2/Hbm-s-Nuclear-Tech-GIT#121]
In main HBM's Nuclear tech mod  for some items while hovering over it you can press F1, and it will bring a menu similar to create mods "Ponder" menu. 
This menu is very helpful for explaining things with little or no documentation on the wiki such as the Mustard Willow leaf and the Silex. It can also better explain other machinery such as the Gas Centrifuge and Particle Accelerator.

**Comment by MellowArpeggiation** [comment]
The WIAJs are there but the F1 hint isn't showing, odd
