### ISSUE TITLE
Large mining drills not effected by different drills

### ISSUE THREAD

**Issue by hypnoshadow** [JameH2/Hbm-s-Nuclear-Tech-GIT#124]
Im not sure if its a bug,but mining drills,even when using a desh drillbit with fortune 4,it was still a single ore every minute,nothing seems to effect it

![image](https://github.com/user-attachments/assets/7d7a10e4-9774-447f-a2c6-b98bb9108f79)

**Comment by hypnoshadow** [comment]
![image](https://github.com/user-attachments/assets/2142c814-8f06-4a67-a9f4-b07c77152af2)

**Comment by MellowArpeggiation** [comment]
Unable to reproduce, tested a steel drillbit and a ferro drillbit simultaneously and received ores in a 2,5x ratio, as expected.
