### ISSUE TITLE
Well... This is awkward.

### ISSUE THREAD

**Issue by thefitnessgrampacertes** [JameH2/Hbm-s-Nuclear-Tech-GIT#134]
So, I just got the mod, loaded it up in 1.7.10, and guess what? It just showed colors! I know it was still Minecraft but my whole screen was the color of the sky. I have no clue what's going on, so I'm going here. Does anyone know what this is and how to solve it? I'll put screenshots to help.
![Screenshot 2024-09-08 013627](https://github.com/user-attachments/assets/ce9f7cfe-2b30-41c6-a8f0-ab11086a0e00)
![Screenshot 2024-09-08 013554](https://github.com/user-attachments/assets/03237e7e-e477-4839-8620-5887197faac3)

**Comment by JameH2** [comment]
Mods folder?

**Comment by FatSassin** [comment]
Have you tried updating graphics drivers or making sure (if you have integrated and normal GPU) that Minecraft uses your normal GPU? Also yes mods folder

**Comment by Darek505** [comment]
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/issues/985

you have 3 solutions to the problem:

1) Graphics driver rollback
2) [Neodymium](https://github.com/makamys/Neodymium) - side fix
3) [CoreTweaks](https://github.com/makamys/CoreTweaks) - targeted fix

more details - https://www.minecraftforum.net/forums/support/java-edition-support/3148472-weird-bug-with-1-7-10-and-only-1-7-10

**Comment by thefitnessgrampacertes** [comment]
its in mods folder, heres proof
![Screenshot 2024-09-08 132809](https://github.com/user-attachments/assets/0fbd2233-d24e-4cc7-9755-3dde11c953f8)

**Comment by thefitnessgrampacertes** [comment]
> [HbmMods#985](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/issues/985)
> 
> you have 3 solutions to the problem:
> 
> 1. Graphics driver rollback
> 2. [Neodymium](https://github.com/makamys/Neodymium) - side fix
> 3. [CoreTweaks](https://github.com/makamys/CoreTweaks) - targeted fix
> 
> more details - https://www.minecraftforum.net/forums/support/java-edition-support/3148472-weird-bug-with-1-7-10-and-only-1-7-10

THANK YOU SO FUCKING MUCH IT WORKS
