### ISSUE TITLE
with gtnh/gtnh nei, The gtnh nei structure Utility does not work properly

### ISSUE THREAD

**Issue by mcmso** [JameH2/Hbm-s-Nuclear-Tech-GIT#136]
gtnh+hbmspace
Cause a crash when previewing a multi-block structure

https://paste.ubuntu.com/p/pgj6wjfKCW/
https://paste.ubuntu.com/p/GYgnVkGGwf/

**Comment by thePalindrome** [comment]
What do you mean by "structure utility"?

I've been using the GTNH NEI with this mod and haven't been having the log spam you're getting, and the end seems to just have a crash with the atmosphere bubble code that occasionally happens (due to chunk loading oddities, iirc)

**Comment by chixiguaya** [comment]
![image](https://github.com/user-attachments/assets/5d4bd7c3-4b53-4ba0-bdad-764af9af40e9)
Adding it to GTNH will cause this interface to fail to open.

**Comment by chixiguaya** [comment]
No problem with joining the original HBM

**Comment by mcmso** [comment]
> No problem with joining the original HBM

zhebanglaowaikanbudongwentiyuanyizaizhexiajibaluanhuiexinren

**Comment by mcmso** [comment]
> No problem with joining the original HBM

zhebanglaowaikanbudongwentiyuanyinzaizhexiajibaluanhuiexinren

**Comment by mcmso** [comment]
> No problem with joining the original HBM

zhebanglaowaikanbudongwentiyuanyinzaizhexiajibaluanhuiexinren
