### ISSUE TITLE
No PLSS oxygen bar

### ISSUE THREAD

**Issue by bearsjunior** [JameH2/Hbm-s-Nuclear-Tech-GIT#138]
### Describe the bug

Latest version on the orbital-mechanics branch.
I have noticed that the PLSS oxygen bar is not appearing on the HUD anymore, despite me wearing a valid spacesuit with the PLSS equipped. I assume this isn't intentional.
![image](https://github.com/user-attachments/assets/28a02ec1-c58b-4138-a53f-e6e1a306d1cf)
![image](https://github.com/user-attachments/assets/bc9fc3c6-3780-4dc4-bb66-b7eab51a9483)

**Comment by MellowArpeggiation** [comment]
Thanks for the report! Should be fixed in that branch now.
