### ISSUE TITLE
Pressure problem

### ISSUE THREAD

**Issue by NeoStarSG** [JameH2/Hbm-s-Nuclear-Tech-GIT#141]
![image](https://github.com/user-attachments/assets/86db23a5-28a7-4fbb-b960-8fccf98e2cc4) 
![image](https://github.com/user-attachments/assets/5d0ca238-405b-4bc3-a8fb-52fe38917d41)
I got a problem, why i cant use infinite water tank while i have enough pressure?

**Comment by MellowArpeggiation** [comment]
It's based on the outside air pressure, but we're probably going to change that to be based on the water table instead (so by default, Eve will no longer support infinite water barrels, but if you release enough steam into the air, you can make any planet support infinite water tanks).
