### ISSUE TITLE
Discharger info tooltip error

### ISSUE THREAD

**Issue by abel1502** [JameH2/Hbm-s-Nuclear-Tech-GIT#143]
The tooltip states the discharger accepts dineutronium, whereas in fact it accepts electronium and produces dineutronium as a result

**Comment by JameH2** [comment]
the discharger is a machine that i have sorely come to regret implementing to the game. it is a testament to the weight of my hubris in the sore years i have endured as a java developer. This abomination curses my memory leading me to weep each night and feel the monotonous progress of life in the morning. If i had to do it all over again i would have heeded myself to avoid such travesty and despair from ever laying its dark grasps on the utopian craftmanship that is my fork.
