### ISSUE TITLE
Orbital station can not be used

### ISSUE THREAD

**Issue by wanghuansen2004** [JameH2/Hbm-s-Nuclear-Tech-GIT#147]
### Describe the bug

I have launched a rocket with a orbital station and a replica of this hard drive successfully,but now it shows that I have not launch.And I m not in a superflat world.
![屏幕截图 2024-09-27 020602](https://github.com/user-attachments/assets/c418619b-4ad4-4a50-ba54-09c820695139)

**Comment by MellowArpeggiation** [comment]
Are you using Optifine?

**Comment by wanghuansen2004** [comment]
> Are you using Optifine?

Yes

**Comment by MellowArpeggiation** [comment]
Ah cool, yeah get rid of it, it causes serious issues with chunkloading entities (like rockets and missiles). If you want improved performance and increased max render distance, use Angelica instead: https://github.com/GTNewHorizons/Angelica

I'm afraid there is nothing we can do to fix issues that Optifine raises, so I'll have to close this issue as wontfix

**Comment by Ilikepotatochips** [comment]
Oh this issue results when you put the hard drives in the Vehicle assembler in the wrong order. Try flipping the order. Double check that also you put in the correct hard drive in to launch

**Comment by MellowArpeggiation** [comment]
Rockets no longer perform a gravity turn if you're using Optifine, which should alleviate the issue.

**Comment by wanghuansen2004** [comment]
> 如果您使用 Optifine，火箭不再执行重力转向，这应该可以缓解这个问题。

The problem is solved,thank you vrey much!
