### ISSUE TITLE
Crash with Energy Control

### ISSUE THREAD

**Issue by MrPhaot** [JameH2/Hbm-s-Nuclear-Tech-GIT#149]
Apparently there is still an issue with Energy Control. 
When I try to run the fork (at least since the version X5064) with Energy Control 0.3.5 it crashes.
I already reported it on the other mod's git. 
#https://github.com/Zuxelus/Energy-Control/issues/84https://github.com/Zuxelus/Energy-Control/issues/84

Thanks in advance!

[crash-2024-09-28_16.28.14-client.txt](https://github.com/user-attachments/files/17174803/crash-2024-09-28_16.28.14-client.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/17174804/fml-client-latest.log)

**Comment by gmhs022** [comment]
Pretty sure it was an issue of outdated stuff on Energy Control's side, try using the base mod because from what I recall it still crashes there since energy control hasn't updated to it yet.

**Comment by Millymilo00** [comment]
Have you tried using the beta release of energy control in it's github releases?
[https://github.com/Zuxelus/Energy-Control/releases/tag/1.7.10-0.3.5e](https://github.com/Zuxelus/Energy-Control/releases/tag/1.7.10-0.3.5e)

**Comment by MrPhaot** [comment]
I tried the beta version of Energy Control (0.3.5**e**) and it worked. Thanks to @Millymilo000 for giving the hint!
