### ISSUE TITLE
Endless ID incompatibility when entering the Orbit dimension

### ISSUE THREAD

**Issue by githubgarry73** [JameH2/Hbm-s-Nuclear-Tech-GIT#155]
Game crashes when entering the orbit with EndlessID installed.

Crash log:
[crash-2024-10-04_16.55.07-server.txt](https://github.com/user-attachments/files/17261344/crash-2024-10-04_16.55.07-server.txt)

**Comment by MellowArpeggiation** [comment]
I've fixed EndlessIDs compat in upstream NTM, I'll make sure those fixes get into the next update, and I'll close this issue when it's all merged
