### ISSUE TITLE
Stardar stuck at loading heightmap

### ISSUE THREAD

**Issue by abel1502** [JameH2/Hbm-s-Nuclear-Tech-GIT#160]
Whenever I select a body in the stardar, or even when I click SLF to select the overworld, the stardar says it's generating heightmap, but then stays that way without ever finishing. 

Worth noting, I am playing on a custom build with the upstream changes (67 commits at the time of writing) merged in. Not sure if it's impacting this behavior or not, though. I did test to see if it was related to the newly introduced tile entity packet caching mechanism, and can confirm it is unrelated (reproducible with caching disabled).

**Comment by abel1502** [comment]
Another potentially relevant detail is that I am using Angelica, and am **not** using Optifine.

**Comment by abel1502** [comment]
Okay, after thorough debugging, it was in fact due to caching, indirectly. `TileEntityStardar#serialize` has a side effect of resetting the `updateHeightmap` flag, and the current implementation of caching happens to invoke `serialize` twice -- once to compare the contents, the second time to send the packet. For my initial tests, I'd commented out the actual short-circuit return, but not the first call to serialize, which was what caused the problem.

I don't think there's an easy way of fixing it on the side of serialization, short of making `BufPacket` cache its result internally. I've also just checked and can confirm that no other implementation of `serialize` has any sort of side effects like this, so I _don't_ think the solution _should_ be done in the caching mechanism either.

On the other hand, fixing this on your side is trivial: just move the `updateHeightmap = false;` from the end of `TileEntityStardar#serialize` to either right after the (only) call to `networkPackNT` over in `TileEntityStardar#updateEntity`, or at the end of an overridden version of `networkPackNT` itself.

**Comment by abel1502** [comment]
Yes, can confirm, it does solve the problem

**Comment by MellowArpeggiation** [comment]
Thanks for the fix! It's merged so I'll close this now
