### ISSUE TITLE
Misleading config options

### ISSUE THREAD

**Issue by abel1502** [JameH2/Hbm-s-Nuclear-Tech-GIT#164]
The configuration options `2.B08_bedrockBismuthSpawn` and `2.B09_bedrockCadmiumSpawn` exist, alongside corresponding bedrock ores, but no spawning logic is present for them (or at least none refers to these config variables). Either the deposit spawning code should be added, or the config and ores themselves removed. As is, it is misleading players into searching for non-existent deposits

**Comment by MellowArpeggiation** [comment]
We're removing these bedrock items entirely in favour of the new bedrock system soon, so there isn't much use in fixing up this issue at this time
