### ISSUE TITLE
It keeps saying station not yet launched

### ISSUE THREAD

**Issue by Fixplslit** [JameH2/Hbm-s-Nuclear-Tech-GIT#168]
### Describe the bug

Please describe the issue in as much detail as possible. Also mention the version of the mod you're running, if it's not the newest. In the case of a crash, please attach a crash log.

**Comment by MellowArpeggiation** [comment]
Please remove Optifine and use any of the other, less destructively shit performance improvement mods, such as Angelica: https://github.com/GTNewHorizons/Angelica
