### ISSUE TITLE
Question about `AtmosphereBlob.contains()` (doesn't work in all directions) | `ChunkAtmosphereManager.proxy.getBlobs` returns an empty list

### ISSUE THREAD

**Issue by kotmatross28729** [JameH2/Hbm-s-Nuclear-Tech-GIT#171]
So, I'm doing ntm space compatibility for enviromine, for this I needed to find the current atmosphere blob and check it's ability to support breathing (`blob.hasFluid(Fluids.AIR, 0.19) || blob.hasFluid(Fluids.OXYGEN, 0.09 )`) 

However, during testing I noticed a very strange thing: 
`contains(ThreeInts)` method sometimes produces false near the walls.  (and also `ChunkAtmosphereManager.proxy.getBlobs()` returns an empty list, but more on that later)

Here's what I found:

1) If: the block is on the Z- and X+ axes: then false will be returned if the block is in front of the player:

https://github.com/user-attachments/assets/48d23cef-48ed-4ade-9d16-4a060f48870d

2) If: the block is on the Z- and X- axes: then false will be returned if the block is diagonally to the left of the player:

https://github.com/user-attachments/assets/94fd5396-c94f-4330-a5af-ad80d9e8ca3e

3) If: the block is on the Z+ and X- axes: then false will be returned if the right side of the block is to the left of the player:

https://github.com/user-attachments/assets/ffb39758-88c6-43c7-967f-c9e25eb01a22

4) If: the block is on the Z+ and X+ axes: then false will NOT be returned , seems to be the expected behavior:

https://github.com/user-attachments/assets/8655f9bd-26f4-4699-9194-b9235a154514

Important for reproduce: the player must always face the Z+ axis direction

Code used for testing:

```java

public static float[] getSurroundingData(EntityLivingBase entityLiving) {
...
   ThreeInts pos = new ThreeInts((int) entityLiving.posX, (int) (entityLiving.posY), (int) entityLiving.posZ);
   List<AtmosphereBlob> currentBlobs = getBlobsWithinRadius(ChunkAtmosphereManager.proxy, entityLiving.worldObj, pos, 256);
      for (AtmosphereBlob blob : currentBlobs) {
            LogManager.getLogger().fatal("currentBlobs size : " + blob.getBlobSize());
            LogManager.getLogger().fatal("currentBlobs contains : " + blob.contains(pos));
      }
...
}
                    
    public static List<AtmosphereBlob> getBlobsWithinRadius(ChunkAtmosphereHandler handler, World world, ThreeInts pos, int radius) {
        try {
            Method method = ChunkAtmosphereHandler.class.getDeclaredMethod("getBlobsWithinRadius", World.class, ThreeInts.class, int.class);
            method.setAccessible(true);
            return (List<AtmosphereBlob>) method.invoke(handler, world, pos, radius);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

```

The same thing without using reflection:
The difference is that then `"currentBlobs size : "`and `"currentBlobs contains : "` are not displayed at all, since `List<AtmosphereBlob> currentBlobs` in such positions is generally empty

```java
                ThreeInts pos = new ThreeInts((int) entityLiving.posX, (int) (entityLiving.posY), (int) entityLiving.posZ);
                List<AtmosphereBlob> currentBlobs = ChunkAtmosphereManager.proxy.getBlobs(entityLiving.worldObj, pos.x, pos.y, pos.z);
                    for (AtmosphereBlob blob : currentBlobs) {
                        LogManager.getLogger().fatal("currentBlobs size : " + blob.getBlobSize());
                        LogManager.getLogger().fatal("currentBlobs contains : " + blob.contains(pos));
                    }
```

for even greater clarity, the scheme(s) for returning false / empty list:

```
A - anything
B - block
E - entity (player)
				
             Z+
             |
    WORKING  |   AAA
    WORKING  |   ABE
    WORKING  |   AAA
             |
X+<----------|---------->X-
             |
    ABA      |   BAA
    AEA      |   AEA
    AAA      |   AAA
             |
             Z-
```
			
			
			
											
			
![Test2](https://github.com/user-attachments/assets/8fc5fa9b-d049-49d8-9608-0207bc869508)

**Comment by MellowArpeggiation** [comment]
Thanks for the very comprehensive report! I'll surely be looking through this and making the system more direction agnostic. Since it's a sign issue there is likely a truncation done where it should instead be floored, so that should be easy to find and fix

**Comment by MellowArpeggiation** [comment]
oh, actually, in your code you're doing a truncation, specifically this line:
```java
ThreeInts pos = new ThreeInts((int) entityLiving.posX, (int) (entityLiving.posY), (int) entityLiving.posZ);
```
that'll be causing the offset issues you're seeing on negative coordinates, not our code. Make sure to floor float/double values rather than casting them directly to ints

**Comment by kotmatross28729** [comment]
EDIT: oh, sorry, didn't see "floor", yes, same thing with that

I also tried using `MathHelper.floor_double(double)` | `Math.round(float)`, but it's the same here.

And although I have another implementation of this (completely unrelated to this), I still wonder what’s the matter. 

I'm apologize if this is indeed a mistake on my side, but I still wanted to clarify this in more detail

**Comment by kotmatross28729** [comment]
I apologize very much for wasting your time, the fault is really mine: I have absolutely no idea how, but now it works, apparently when I replaced `(int)` with `MathHelper.floor_double`, the jar file didn't build correctly, which is why it used the same `(int)` (Maybe because of some test functions that I tried to implement, build failed, and I actually used the same file without changes, and for some reason I thought that `MathHelper.floor_double` didn't affect)

Again, I apologize for the inconvenience, in the future I will be more careful when creating reports, thank you!

**Comment by Darek505** [comment]
Wait, but isn't truncation acceptable in this case?

If the entity position is 9, or 9.999, it still doesn't go beyond 9, so (int) 9.999 should work?

**Comment by MellowArpeggiation** [comment]
> Wait, but isn't truncation acceptable in this case?
> 
> If the entity position is 9, or 9.999, it still doesn't go beyond 9, so (int) 9.999 should work?

for positive numbers yes, but for negative numbers it introduces off-by-one errors. the floor of `-0.1` is `-1` but the truncated result is `0`.
