### ISSUE TITLE
`TileEntityMachineGasFlare` works in a vacuum

### ISSUE THREAD

**Issue by kotmatross28729** [JameH2/Hbm-s-Nuclear-Tech-GIT#177]
Title, I don’t know if it’s intended that way, but I think not. `TileEntityMachineGasFlare` doesn't have the `breatheAir` method from `TileEntityMachineBase` in checks, so you can burn gas on the moon:

![2024-11-17_19 14 18](https://github.com/user-attachments/assets/90ecaf3f-f919-4bb5-ac58-11c1fa509dde)

**Comment by MellowArpeggiation** [comment]
~~Fixed in bccda5d~~ wrong issue, sorry
