### ISSUE TITLE
Ciws crashing

### ISSUE THREAD

**Issue by Dimitriyc** [JameH2/Hbm-s-Nuclear-Tech-GIT#189]
When CIWS firing, the game crashing. 
In basic NTM i dont have this issue.

**Comment by Dimitriyc** [comment]
Update
I think this crashing start after using civilian airliner designating tool.

**Comment by MellowArpeggiation** [comment]
can you attach a crash log please?

**Comment by MellowArpeggiation** [comment]
CIWS crash fixed in next update
