### ISSUE TITLE
Chicago Pile ignores Neutron Radiation config

### ISSUE THREAD

**Issue by thePalindrome** [JameH2/Hbm-s-Nuclear-Tech-GIT#42]
Even when `B:HAZ_01_disableNeutrons=true`, the chicago pile continues to add neutron radiation to everything at an extremely high degree, even the armor pieces (normal neutron radiation doesn't do that, even when enabled). Given the historical issues with the neutron radiation feature, this should probably be fixed so players can opt-out of that mechanic

**Comment by JameH2** [comment]
fixed, tested, and giggle gaggled

**Comment by thePalindrome** [comment]
In addition, I had a stack of 11 carrots to test this with, and new carrots couldn't stack on top of them. Oddly, they and a small handful of other items didn't get visibly effected by the neutron radiation, although it seems something still got messed up in their NBT

**Comment by JameH2** [comment]
in the new version, decontamination methods SHOULD remove stacktagcompounds entirely

**Comment by thePalindrome** [comment]
They should, but it seems to not be as of x5500 (the latest as of this writing)

**Comment by JameH2** [comment]
what specificially isnt decontaminating?

**Comment by JameH2** [comment]
https://user-images.githubusercontent.com/75378928/236406131-e9f99b4d-5c2c-4ae5-8f7e-dfd77d41fc72.mp4

**Comment by JameH2** [comment]
ive tested it here and it seems to work just fine for me

**Comment by thePalindrome** [comment]
I had 11 carrots in my inventory. They weren't marked as radioactive, but seem to not merge with anything else. Same with a battery and an energy storage block (the white one). Is there anything weird that goes on with things that already have NBT or are stacked?
