### ISSUE TITLE
Curium nugget->billet recipes are slightly broken

### ISSUE THREAD

**Issue by thePalindrome** [JameH2/Hbm-s-Nuclear-Tech-GIT#43]
Curium 242 billets *might* be uncraftable, as the 247 billets are also craftable via the 242 nuggets. In addition, every curium nugget to billet recipe is quadruplicated; which, while less of an issue, makes it a bit harder to navigate imo

**Comment by TheNewGuy19** [comment]
yeah i did a little fucky-wucky, i james fixed the nuggies, and what do you mean with the second bit?

**Comment by JameH2** [comment]
wait i thought i fixed this
oh well lemme check

**Comment by JameH2** [comment]
re

**Comment by thePalindrome** [comment]
![2023-05-05_05 00 57](https://user-images.githubusercontent.com/1844681/236417602-0221e195-63a1-42e4-91f7-996cf5b2f36c.png)

Sadly it seems to not be fixed, even with the release you made a half hour ago (This also demonstrates the second part of the bug)

**Comment by JameH2** [comment]
bob told me to leave it in

**Comment by JameH2** [comment]
soley due to how oredict works and such

**Comment by JameH2** [comment]
what i did fix was curium ingots being duplicate- oh ffs

**Comment by TheNewGuy19** [comment]
what the fuck did i do

**Comment by JameH2** [comment]
nothing i fucked up

**Comment by TheNewGuy19** [comment]
okay good yippee

**Comment by JameH2** [comment]
as for neutron rads, i literally cannot replicate the issue you might just need to wait a few seconds longer

**Comment by JameH2** [comment]
even with the exact same situation you tried

**Comment by thePalindrome** [comment]
We'll chalk it up to cosmic radiation or something. It might've been that the chicago pile did silently add an nbt tag or something that went away after I decontaminated the carrots (I hadn't done that before since they weren't radioactive). Either way it shouldn't be an issue now that I've disabled neutron radiation in my save (in part because when it effects your armor you get kindof screwed)
