### ISSUE TITLE
Opening this mod's achievements screen (on the space travel 2.5 branch) crashes the game

### ISSUE THREAD

**Issue by TheMCSpacePro** [JameH2/Hbm-s-Nuclear-Tech-GIT#84]
When I attempted to open the achievements screen, my game crashed (see log below)

[https://mclo.gs/02XAQMB](https://mclo.gs/02XAQMB)

**Comment by MellowArpeggiation** [comment]
This has been fixed with the latest commit, had a dangling test achievement in there. Thanks for the report!
