### ISSUE TITLE
Crashes whene entering the world

### ISSUE THREAD

**Issue by PlutoSmile0** [JameH2/Hbm-s-Nuclear-Tech-GIT#86]
[crash-2024-08-08_12.47.47-client.txt](https://github.com/user-attachments/files/16541442/crash-2024-08-08_12.47.47-client.txt)

I don't have any extra mods installed

![Снимок](https://github.com/user-attachments/assets/16c71e6d-d372-4de9-912f-3ebacfb5135c)

**Comment by MellowArpeggiation** [comment]
Could you tell me what you were doing at the time of the crash? The log doesn't have enough information and I'm guessing it'd have to be an issue with the rocket entity

**Comment by PlutoSmile0** [comment]
> Could you tell me what you were doing at the time of the crash? The log doesn't have enough information and I'm guessing it'd have to be an issue with the rocket entity

I just created a world and immediately entered it
I couldn't do anything

**Comment by MellowArpeggiation** [comment]
Does it occur every time you load that world?

**Comment by PlutoSmile0** [comment]
> Does it occur every time you load that world?

Yes

**Comment by MellowArpeggiation** [comment]
Can you zip up and send the world please?

**Comment by PlutoSmile0** [comment]
> Can you zip up and send the world please?
[New World--.zip](https://github.com/user-attachments/files/16541577/New.World--.zip)

Here

**Comment by MellowArpeggiation** [comment]
Can't reproduce with the world, I had a look at the decompiled MC source to try and figure it out. This isn't an issue with this mod at least.

Can you check that your minimum framerate isn't set to 0? You may have had a config from a different version messing with your current mod setup. (I _highly_ recommend not using the default Microsoft launcher for this reason! I use Prism Launcher)

**Comment by PlutoSmile0** [comment]
> Can't reproduce with the world, I had a look at the decompiled MC source to try and figure it out. This isn't an issue with this mod at least.
> 
> Can you check that your minimum framerate isn't set to 0? You may have had a config from a different version messing with your current mod setup. (I _highly_ recommend not using the default Microsoft launcher for this reason! I use Prism Launcher)

OMG Thank you!
Im soo dumb
