### ISSUE TITLE
Crashes during loading.

### ISSUE THREAD

**Issue by TehDrpStr** [JameH2/Hbm-s-Nuclear-Tech-GIT#89]
Had a crash with my mod setup before, removed literally all of them and just moved HBM's NTM over. Game crashes.
[crash-2024-08-08_13.30.03-client.txt](https://github.com/user-attachments/files/16552082/crash-2024-08-08_13.30.03-client.txt)

**Comment by Nirmetron** [comment]
Skill issue

**Comment by Nirmetron** [comment]
Also James is trying to fix your issue, don't worry

**Comment by MellowArpeggiation** [comment]
Can you try creating a new instance within Prism without any apostrophes? It seems to be struggling to load content from the instance folder.

**Comment by TehDrpStr** [comment]
That was it. No issue with regular HBM's, apparently this version has problems with an apostrophe though.
