### ISSUE TITLE
Recent bugs

### ISSUE THREAD

**Issue by Wector-Error** [JameH2/Hbm-s-Nuclear-Tech-GIT#90]
Bad blueprints at the Martian base

![image](https://github.com/user-attachments/assets/0f22398a-d84f-4144-bdb6-1c1d5d045041)

Incorrect StarDar crafting
![image (1)](https://github.com/user-attachments/assets/993ae8ed-0766-4529-9112-be2d9915b453)

In addition, some mobs from other mods appear on planets, which is why they die in batches
![image](https://github.com/user-attachments/assets/7bc80214-b72e-49aa-a339-294ecd933071)

**Comment by JameH2** [comment]
blueprints are like that, but they can be useful in other ways...
stardar recipe is fixed, will be in next release

**Comment by MellowArpeggiation** [comment]
The blueprints are only as useful as the paper they're printed on...

;)

**Comment by Wector-Error** [comment]
> чертежи такие, но они могут быть полезны другими способами ... рецепт stardar исправлен, будет в следующем выпуске

WHEN will this issue be released?

**Comment by Wector-Error** [comment]
> The blueprints are only as useful as the paper they're printed on...
> 
> ;)

@MellowArpeggiation WHEN will this issue be released?

**Comment by Wector-Error** [comment]
> blueprints are like that, but they can be useful in other ways... stardar recipe is fixed, will be in next release

@JameH2  WHEN will this issue be released?

**Comment by MellowArpeggiation** [comment]
Please stop spamming, it won't happen any faster

**Comment by MellowArpeggiation** [comment]
All these reported issues are resolved, except for the broken templates, it's (semi-)intended - you can't progress without turning them back into paper.
