### ISSUE TITLE
player suffocates when hitbox is not in solid block

### ISSUE THREAD

**Issue by PlutoSmile0** [JameH2/Hbm-s-Nuclear-Tech-GIT#92]
I'm sure they noticed this without me, but still...
When your hitbox is not in a solid block - you start to choke
Of course, this is only on other planets without oxygen

![2024-08-11_14 52 48](https://github.com/user-attachments/assets/731220b8-7328-4bce-8ae2-9592e9245d07)
![2024-08-11_14 52 52](https://github.com/user-attachments/assets/f85501c9-7534-4b9c-8cea-2582a69b9d5a)

**Comment by MellowArpeggiation** [comment]
The recently committed fix does prevent this issue occurring, but the doors aren't correctly sealing/unsealing at the root of the multi-block, so this could still recur in corner cases until fixed properly
