### ISSUE TITLE
vacuum soldering machine doesnt work

### ISSUE THREAD

**Issue by ecstxasy** [JameH2/Hbm-s-Nuclear-Tech-GIT#94]
i can create a vacuum with the airvents however for none of its recipes is it even possible to put in all the ingredients it just wont go in

**Comment by MellowArpeggiation** [comment]
Like the regular soldering machine, the slots require specific items. Shift-clicking should automatically place the items into the correct slots.

**Comment by ecstxasy** [comment]
yes but they do not go into the correct slots; they dont go anywhere

**Comment by MellowArpeggiation** [comment]
I'm confused by your first post, there is currently no way to create an artificial vacuum in the mod (coming soon), you'll need to be on a celestial body with a vacuum to use the machine (like Mun/Minmus)

**Comment by MellowArpeggiation** [comment]
Fixed an issue with the vacuum solderer working in pressurized rooms on atmosphereless bodies (it requires a vacuum)
