### ISSUE TITLE
Crash when starting the game

### ISSUE THREAD

**Issue by Titodelo** [JameH2/Hbm-s-Nuclear-Tech-GIT#96]
### Describe the bug
[crash-2024-08-11_21.31.35-client.txt](https://github.com/user-attachments/files/16576866/crash-2024-08-11_21.31.35-client.txt)

My game crashes just when I get to the start screen, I'm sharing the crash log to see if you can help me. It says it's a problem with the HBM with some sound option, but I don't quite understand, thank you very much in advance.

**Comment by MellowArpeggiation** [comment]
Looks like it's attempting to play game music on the menu, should be fixed in the next release
