### ISSUE TITLE
Missing recipies and items for nei

### ISSUE THREAD

**Issue by Hacker6400** [JameH2/Hbm-s-Nuclear-Tech-GIT#99]
I was looking for recepies for raw bedrock ore when i notice that is missing the raw bedrock ore and the bedrock ore processor and there is no recepies for the raw bedrock ore

**Comment by Hacker6400** [comment]
Im using nei from gt:nh

**Comment by MellowArpeggiation** [comment]
The new bedrock ore processing chain is currently disabled as we rework it to fit our goals for space, you can use the Survey Scanner to find bedrock ore deposits, and this wiki page will show you what bedrock ores are available on each planet: https://nucleartech.wiki/wiki/NTM:_Space

**Comment by Hacker6400** [comment]
But there's still the processing recepies for them?

**Comment by MellowArpeggiation** [comment]
Yeah I failed to remove visibility for all BRO processing, shouldn't be an issue for too long once we have time to tackle it properly
